/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { Download, FileJson, FileSpreadsheet, Copy, Check, ShieldAlert, Terminal, Package, FileText } from 'lucide-react';
import { AnalysisResult } from '../../analyzer/models/types.ts';

interface ExportTabProps {
  result: AnalysisResult;
}

export const ExportTab: React.FC<ExportTabProps> = ({ result }) => {
  const [copied, setCopied] = useState(false);

  const exportPayload = {
    metadata: {
      generatedBy: 'SmartShield - Delegatecall Attack-Path Search',
      timestamp: new Date().toISOString(),
      compilerVersion: result.ir.compilerVersion,
      status: 'CANDIDATE_ATTACK_PATHS_GENERATED',
      notice:
        'Candidate paths are generated by static analysis. They are not confirmed vulnerabilities. Runtime/symbolic validation is required.',
    },
    summary: result.summary,
    candidateAttackPaths: result.candidateAttackPaths,
    ir: {
      contracts: result.ir.contracts.map((c) => ({
        name: c.name,
        kind: c.kind,
        inheritance: c.inheritance,
        stateVariablesCount: c.stateVariables.length,
        functionsCount: c.functions.length,
      })),
      storageLayout: result.ir.storageLayout,
      delegatecalls: result.ir.delegatecalls,
      sensitiveOperations: result.ir.sensitiveOperations,
    },
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(exportPayload, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `smartshield-candidate-paths-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPackage = async () => {
    try {
      const res = await fetch('/api/analysis/current/package');
      let pkgData;
      if (res.ok) {
        pkgData = await res.json();
      } else {
        // Construct package client-side
        pkgData = {
          'manifest.json': {
            schema_version: '1.0',
            package_name: 'SmartShield Analysis Package',
            timestamp: new Date().toISOString(),
            tool: 'SmartShield Static Delegatecall Analyzer',
            methodology: 'DelegateTracker Read-Write Data Flow Capture Algorithm',
            status: 'STATIC_CANDIDATES_GENERATED',
            summary: result.summary,
          },
          'contract_ir.json': result.ir,
          'candidate_paths.json': result.candidateAttackPaths,
          'delegatecalls.json': result.ir.delegatecalls,
          'storage_layout.json': result.ir.storageLayout,
          'call_graph.json': result.ir.calls,
          'cfg.json': result.ir.controlFlow,
          'read_write.json': result.ir.functions.map((f) => ({
            contract: f.contract,
            function: f.name,
            reads: f.reads,
            writes: f.writes,
          })),
        };
      }

      const blob = new Blob([JSON.stringify(pkgData, null, 2)], {
        type: 'application/json',
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `smartshield-analysis-package-${Date.now()}.json`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error('Failed to download package:', e);
    }
  };

  const handleDownloadReport = () => {
    const lines = [
      '# SmartShield Static Analysis Report',
      `**Generated:** ${new Date().toISOString()}`,
      `**Tool:** SmartShield Delegatecall Attack-Path Search`,
      `**Target Compiler:** ${result.ir.compilerVersion}`,
      '',
      '## Executive Summary',
      `- Contracts Analyzed: ${result.summary.contractsCount}`,
      `- Functions Mapped: ${result.summary.functionsCount}`,
      `- State Variables: ${result.summary.stateVariablesCount}`,
      `- Delegatecalls Detected: ${result.summary.delegatecallCount}`,
      `- Sensitive Operations: ${result.summary.sensitiveOperationsCount}`,
      `- Candidate Attack Paths: ${result.summary.candidateAttackPathsCount}`,
      '',
      '## Candidate Attack Paths (Validation Required)',
    ];

    if (result.candidateAttackPaths.length === 0) {
      lines.push('No candidate attack paths detected.');
    } else {
      result.candidateAttackPaths.forEach((p, idx) => {
        lines.push(`### Candidate Path #${idx + 1}: ${p.id}`);
        lines.push(`- **Type:** ${p.vulnerability_type || p.vulnerabilityType}`);
        lines.push(`- **Status:** ${p.status} (Stage 1 Static Candidate)`);
        lines.push(`- **Vulnerability Variable:** \`${p.vulnerabilityVariable}\` (Slot: ${p.storage.slot}, Offset: ${p.storage.offset})`);
        lines.push(`- **Writer Function:** \`${p.writerFunction}()\``);
        lines.push(`- **Reader Function:** \`${p.readerFunction}()\``);
        lines.push(`- **Sink Operation:** \`${p.sensitiveOperation.type}\` in \`${p.sensitiveOperation.function}()\``);
        lines.push(`- **Reason:** ${p.reason}`);
        lines.push('');
      });
    }

    lines.push('---');
    lines.push('**Notice:** All candidate findings are generated via static analysis. Dynamic or symbolic validation is required to verify constraint satisfiability.');

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `smartshield-report-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadCSV = async () => {
    try {
      const res = await fetch('/api/attack-paths/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ format: 'csv' }),
      });
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `smartshield-candidate-paths-${Date.now()}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error('CSV export failed:', e);
    }
  };

  const handleCopyJSON = () => {
    navigator.clipboard.writeText(JSON.stringify(exportPayload.candidateAttackPaths, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8">
      {/* Disclaimer Banner */}
      <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-200 text-xs flex items-start space-x-3">
        <ShieldAlert className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="font-bold text-amber-300">
            NON-CLAIM OF CONFIRMED VULNERABILITY (STATIC ANALYSIS SCOPE)
          </p>
          <p className="text-slate-300 leading-relaxed">
            This export contains Stage 1 candidate data flow paths intended for validation. It must not be presented to clients as an audit report of confirmed exploits without symbolic constraint verification.
          </p>
        </div>
      </div>

      {/* Export Action Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Machine-Readable Package Card */}
        <div className="bg-slate-900 border border-blue-500/30 rounded-2xl p-6 shadow-xl space-y-4 flex flex-col justify-between">
          <div className="space-y-3">
            <div className="w-10 h-10 rounded-xl bg-blue-500/10 text-blue-400 flex items-center justify-center">
              <Package className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Full Analysis Package</h3>
              <p className="text-xs text-slate-400 mt-1">
                Complete multi-file archive containing manifest, contract IR, storage layout, call graph, and candidate paths.
              </p>
            </div>
          </div>

          <div className="pt-2">
            <button
              onClick={handleDownloadPackage}
              className="w-full px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center justify-center space-x-2 transition shadow-lg shadow-blue-500/20 cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download Package (JSON)</span>
            </button>
          </div>
        </div>

        {/* JSON Export Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4 flex flex-col justify-between">
          <div className="space-y-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-500/10 text-cyan-400 flex items-center justify-center">
              <FileJson className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Candidate Paths JSON</h3>
              <p className="text-xs text-slate-400 mt-1">
                Standardized schema matching the <code className="text-blue-300">CandidateAttackPath[]</code> specification.
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2 pt-2">
            <button
              onClick={handleDownloadJSON}
              className="flex-1 px-3 py-2.5 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold flex items-center justify-center space-x-1.5 transition cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download</span>
            </button>

            <button
              onClick={handleCopyJSON}
              className="px-3 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium border border-slate-700 flex items-center space-x-1.5 transition cursor-pointer"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
          </div>
        </div>

        {/* Markdown & CSV Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4 flex flex-col justify-between">
          <div className="space-y-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Security Report & CSV</h3>
              <p className="text-xs text-slate-400 mt-1">
                Human-readable Markdown audit report and flat CSV spreadsheet for audit tracking.
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2 pt-2">
            <button
              onClick={handleDownloadReport}
              className="flex-1 px-3 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold flex items-center justify-center space-x-1.5 transition cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Report (MD)</span>
            </button>

            <button
              onClick={handleDownloadCSV}
              className="flex-1 px-3 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 flex items-center justify-center space-x-1.5 transition cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>CSV</span>
            </button>
          </div>
        </div>
      </div>

      {/* JSON Preview Panel */}
      <div className="bg-slate-950 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-xs font-mono font-bold text-slate-300 flex items-center space-x-2">
            <Terminal className="w-4 h-4 text-cyan-400" />
            <span>CandidateAttackPath JSON Preview</span>
          </span>
          <span className="text-[11px] font-mono text-slate-500">
            {result.candidateAttackPaths.length} objects
          </span>
        </div>

        <pre className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-cyan-300 overflow-x-auto max-h-[380px] scrollbar-thin">
          {JSON.stringify(result.candidateAttackPaths, null, 2)}
        </pre>
      </div>
    </div>
  );
};
