/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { Download, FileJson, FileSpreadsheet, Copy, Check, ShieldAlert, Terminal } from 'lucide-react';
import { AnalysisResult } from '../../analyzer/models/types.ts';

interface ExportTabProps {
  result: AnalysisResult;
}

export const ExportTab: React.FC<ExportTabProps> = ({ result }) => {
  const [copied, setCopied] = useState(false);

  const exportPayload = {
    metadata: {
      generatedBy: 'SmartShield Group 1 - Delegatecall Attack-Path Search',
      timestamp: new Date().toISOString(),
      compilerVersion: result.ir.compilerVersion,
      status: 'CANDIDATE_ATTACK_PATHS_GENERATED',
      notice:
        'Candidate paths are generated by static analysis. They are not confirmed vulnerabilities. Runtime/symbolic validation is required.',
    },
    summary: result.summary,
    candidateAttackPaths: result.candidateAttackPaths,
    ir: {
      contracts: result.ir.contracts.map((c) => ({
        name: c.name,
        kind: c.kind,
        inheritance: c.inheritance,
        stateVariablesCount: c.stateVariables.length,
        functionsCount: c.functions.length,
      })),
      storageLayout: result.ir.storageLayout,
      delegatecalls: result.ir.delegatecalls,
      sensitiveOperations: result.ir.sensitiveOperations,
    },
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(exportPayload, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `smartshield-candidate-paths-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadCSV = async () => {
    try {
      const res = await fetch('/api/attack-paths/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ format: 'csv' }),
      });
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `smartshield-candidate-paths-${Date.now()}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error('CSV export failed:', e);
    }
  };

  const handleCopyJSON = () => {
    navigator.clipboard.writeText(JSON.stringify(exportPayload.candidateAttackPaths, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8">
      {/* Disclaimer Banner */}
      <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-200 text-xs flex items-start space-x-3">
        <ShieldAlert className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="font-bold text-amber-300">
            NON-CLAIM OF CONFIRMED VULNERABILITY (GROUP 1 SCOPE CONSTRAINT)
          </p>
          <p className="text-slate-300 leading-relaxed">
            This export contains Stage 1 candidate data flow paths intended specifically for handoff to a Group 2
            symbolic validation engine. It must not be presented to clients as an audit report of confirmed vulnerabilities.
          </p>
        </div>
      </div>

      {/* Export Action Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* JSON Export Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
          <div className="w-10 h-10 rounded-xl bg-blue-500/10 text-blue-400 flex items-center justify-center">
            <FileJson className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white">Group 2 Standard JSON Format</h3>
            <p className="text-xs text-slate-400 mt-1">
              Complete standardized schema matching the <code className="text-blue-300">CandidateAttackPath[]</code>{' '}
              specification required for symbolic execution.
            </p>
          </div>

          <div className="flex items-center space-x-3 pt-2">
            <button
              onClick={handleDownloadJSON}
              className="px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center space-x-2 transition shadow-lg shadow-blue-500/20 cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download JSON</span>
            </button>

            <button
              onClick={handleCopyJSON}
              className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium border border-slate-700 flex items-center space-x-2 transition cursor-pointer"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied Paths!' : 'Copy to Clipboard'}</span>
            </button>
          </div>
        </div>

        {/* CSV Export Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center">
            <FileSpreadsheet className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white">Tabular CSV Export</h3>
            <p className="text-xs text-slate-400 mt-1">
              Flat spreadsheet format for audit logbook tracking, reviewing storage slots, writer functions, and
              sensitive sink locations.
            </p>
          </div>

          <div className="pt-2">
            <button
              onClick={handleDownloadCSV}
              className="px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold flex items-center space-x-2 transition shadow-lg shadow-emerald-500/20 cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download CSV</span>
            </button>
          </div>
        </div>
      </div>

      {/* JSON Preview Panel */}
      <div className="bg-slate-950 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-xs font-mono font-bold text-slate-300 flex items-center space-x-2">
            <Terminal className="w-4 h-4 text-cyan-400" />
            <span>CandidateAttackPath JSON Preview (Group 2 Interface)</span>
          </span>
          <span className="text-[11px] font-mono text-slate-500">
            {result.candidateAttackPaths.length} objects
          </span>
        </div>

        <pre className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-cyan-300 overflow-x-auto max-h-[380px] scrollbar-thin">
          {JSON.stringify(result.candidateAttackPaths, null, 2)}
        </pre>
      </div>
    </div>
  );
};
