/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleGenAI } from '@google/genai';
import { Router } from 'express';
import { AnalyzerService } from '../analyzer/index.ts';
import { AnalysisInput, CandidateAttackPath } from '../analyzer/models/types.ts';
import { DEMO_CONTRACTS } from '../analyzer/examples/demoContracts.ts';
import { analysisStore } from './store.ts';

export const apiRouter = Router();

// POST /api/analyze
apiRouter.post('/analyze', (req, res) => {
  try {
    let { sources, source, compilerVersion = '0.8.20' } = req.body;

    if (!sources || !Array.isArray(sources) || sources.length === 0) {
      if (typeof source === 'string' && source.trim()) {
        sources = [{ filename: 'Contract.sol', content: source }];
      } else {
        return res.status(400).json({ error: 'Solidity source code is required' });
      }
    }

    const input: AnalysisInput = {
      sources,
      compilerVersion,
    };

    const result = AnalyzerService.analyze(input);
    const analysisId = 'analysis-' + Date.now();
    analysisStore.setResult(analysisId, result);

    return res.json({
      id: analysisId,
      ...result,
    });
  } catch (err: any) {
    console.error('Error during analysis:', err);
    return res.status(500).json({
      error: 'Internal static analysis failure',
      details: err?.message || String(err),
    });
  }
});

// GET /api/attack-paths
apiRouter.get('/attack-paths', (req, res) => {
  const paths = analysisStore.getAllAttackPaths();
  return res.json(paths);
});

// POST /api/attack-paths/export
apiRouter.post('/attack-paths/export', (req, res) => {
  const { format = 'json' } = req.body;
  const paths = analysisStore.getAllAttackPaths();
  const currentResult = analysisStore.getResult();

  if (format === 'csv') {
    const headers = [
      'Candidate ID',
      'Vulnerability Type',
      'Caller Contract',
      'Callee Contract',
      'Writer Function',
      'Vulnerability Variable',
      'Reader Function',
      'Sensitive Operation',
      'Storage Slot',
      'Storage Offset',
      'Confidence',
      'Status',
      'Validation Required',
      'Reason',
    ];

    const rows = paths.map((p) => [
      p.id,
      p.vulnerabilityType,
      p.callerContract || 'N/A',
      p.calleeContract || 'N/A',
      p.writerFunction,
      p.vulnerabilityVariable,
      p.readerFunction,
      `${p.sensitiveOperation.type} in ${p.sensitiveOperation.function}`,
      p.storage.slot ?? 'N/A',
      p.storage.offset ?? '0',
      p.storage.confidence,
      p.status,
      p.validationRequired ? 'YES' : 'NO',
      `"${p.reason.replace(/"/g, '""')}"`,
    ]);

    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', 'attachment; filename="smartshield-candidate-attack-paths.csv"');
    return res.send(csvContent);
  }

  return res.json({
    timestamp: new Date().toISOString(),
    tool: 'SmartShield Group 1 - Delegatecall Attack-Path Search',
    methodology: 'DelegateTracker Read-Write Data Flow AST Analysis',
    status: 'STATIC_CANDIDATES_GENERATED',
    validationNotice:
      'Candidate paths are generated by static analysis. They are not confirmed vulnerabilities. Runtime/symbolic validation is required by Group 2.',
    summary: currentResult?.summary || null,
    candidateAttackPaths: paths,
  });
});

// GET /api/contracts/:id
apiRouter.get('/contracts/:id', (req, res) => {
  const contract = analysisStore.getContract(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: `Contract '${req.params.id}' not found in active analysis.` });
  }
  return res.json(contract);
});

// GET /api/contracts/:id/functions
apiRouter.get('/contracts/:id/functions', (req, res) => {
  const contract = analysisStore.getContract(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: `Contract '${req.params.id}' not found.` });
  }
  return res.json(contract.functions);
});

// GET /api/contracts/:id/read-write
apiRouter.get('/contracts/:id/read-write', (req, res) => {
  const contract = analysisStore.getContract(req.params.id);
  if (!contract) {
    return res.status(404).json({ error: `Contract '${req.params.id}' not found.` });
  }
  const rwData = contract.functions.map((f) => ({
    function: f.name,
    reads: f.reads,
    writes: f.writes,
    visibility: f.visibility,
    modifiers: f.modifiers,
    externalReachability: f.externalReachability,
  }));
  return res.json(rwData);
});

// GET /api/contracts/:id/delegatecalls
apiRouter.get('/contracts/:id/delegatecalls', (req, res) => {
  const result = analysisStore.getResult();
  if (!result) {
    return res.status(404).json({ error: 'No active analysis found.' });
  }
  const dcs = result.ir.delegatecalls.filter(
    (d) => d.contract.toLowerCase() === req.params.id.toLowerCase()
  );
  return res.json(dcs);
});

// GET /api/contracts/:id/storage
apiRouter.get('/contracts/:id/storage', (req, res) => {
  const result = analysisStore.getResult();
  if (!result) {
    return res.status(404).json({ error: 'No active analysis found.' });
  }
  const slots = result.ir.storageLayout.filter(
    (s) => s.contract.toLowerCase() === req.params.id.toLowerCase()
  );
  return res.json(slots);
});

// GET /api/contracts/:id/attack-paths
apiRouter.get('/contracts/:id/attack-paths', (req, res) => {
  const paths = analysisStore.getAllAttackPaths().filter(
    (p) =>
      (p.callerContract && p.callerContract.toLowerCase() === req.params.id.toLowerCase()) ||
      (p.calleeContract && p.calleeContract.toLowerCase() === req.params.id.toLowerCase())
  );
  return res.json(paths);
});

// GET /api/demos
apiRouter.get('/demos', (req, res) => {
  return res.json(DEMO_CONTRACTS);
});

// POST /api/ai-explain-path
// High thinking security report assistant for candidate attack paths
apiRouter.post('/ai-explain-path', async (req, res) => {
  const { path: candidatePath, sourceCode } = req.body;

  if (!candidatePath) {
    return res.status(400).json({ error: 'Candidate attack path data is required.' });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === 'MY_GEMINI_API_KEY') {
    return res.json({
      explanation: `### Static Candidate Path Assessment: ${candidatePath.id}
**Type:** ${candidatePath.vulnerabilityType}
**Vulnerability Variable:** \`${candidatePath.vulnerabilityVariable}\`
**Path:** \`${candidatePath.writerFunction}()\` -> \`${candidatePath.vulnerabilityVariable}\` -> \`${candidatePath.readerFunction}()\` -> \`${candidatePath.sensitiveOperation.type}\`

**Static Assessment:**
The static analysis identified a direct data-flow connection between \`${candidatePath.writerFunction}\` which mutates state variable \`${candidatePath.vulnerabilityVariable}\` at storage slot ${candidatePath.storage.slot || '0'}, and \`${candidatePath.readerFunction}\` which evaluates that variable before executing a sensitive ${candidatePath.sensitiveOperation.type} operation.

*Note: Group 1 establishes this static candidate path. Group 2 symbolic validation is required to verify reachability and constraint satisfiability.*`,
      mode: 'STATIC_FALLBACK',
    });
  }

  try {
    const ai = new GoogleGenAI();
    const prompt = `You are a specialized smart-contract security researcher reviewing a candidate attack path generated by SmartShield Group 1 (inspired by the DelegateTracker static analysis paper).

Candidate Attack Path Details:
ID: ${candidatePath.id}
Vulnerability Type: ${candidatePath.vulnerabilityType}
Caller Contract: ${candidatePath.callerContract}
Callee Contract: ${candidatePath.calleeContract}
Delegatecall Location: ${JSON.stringify(candidatePath.delegatecallLocation)}
Writer Function: ${candidatePath.writerFunction}
Reader Function: ${candidatePath.readerFunction}
Vulnerability Variable: ${candidatePath.vulnerabilityVariable}
Storage Slot: ${candidatePath.storage.slot}, Offset: ${candidatePath.storage.offset}
Reason: ${candidatePath.reason}

Source Code Context:
\`\`\`solidity
${sourceCode || 'Source not provided'}
\`\`\`

Task:
Provide a rigorous technical explanation of:
1. The read-write data flow mechanism between ${candidatePath.writerFunction} and ${candidatePath.readerFunction}.
2. The EVM storage slot implication (slot ${candidatePath.storage.slot}), especially in the context of delegatecall execution.
3. Why this remains a CANDIDATE path rather than a confirmed exploit at Stage 1.
4. Specific symbolic constraints and verification objectives recommended for Group 2 (e.g., Z3 solver satisfiability, msg.sender constraints, path feasibility).

Format cleanly in markdown.`;

    // High thinking mode with gemini-3.1-pro-preview as specified
    const response = await ai.models.generateContent({
      model: 'gemini-3.1-pro-preview',
      contents: prompt,
      config: {
        thinkingConfig: {
          thinkingLevel: 'HIGH' as any,
        },
      },
    });

    const explanation = response.text || 'Unable to generate analysis text.';
    return res.json({
      explanation,
      mode: 'GEMINI_3_1_PRO_HIGH_THINKING',
    });
  } catch (err: any) {
    console.warn('Gemini high thinking explanation failed, falling back to static summary:', err);
    return res.json({
      explanation: `### Static Candidate Path Assessment: ${candidatePath.id}
**Type:** ${candidatePath.vulnerabilityType}
**Vulnerability Variable:** \`${candidatePath.vulnerabilityVariable}\`
**Path:** \`${candidatePath.writerFunction}()\` -> \`${candidatePath.vulnerabilityVariable}\` -> \`${candidatePath.readerFunction}()\`

**Reasoning:**
${candidatePath.reason}

*Note: Group 2 symbolic validation must test reachability constraints for ${candidatePath.writerFunction} and verify if caller identity or slot alignment permits unauthorized execution.*`,
      mode: 'STATIC_FALLBACK',
    });
  }
});
